services:
  mysqldb:
    image: mysql:9-oraclelinux9
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - service-network
    restart: unless-stopped
    secrets:
      - db_password
      - db_root_password

  flyway:
    image: flyway/flyway
    container_name: flyway-migration
    command: -configFiles=/run/secrets/flyway_config migrate
    environment:
      - FLYWAY_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?sslMode=PREFERRED&allowPublicKeyRetrieval=true
      - FLYWAY_USER=root
    volumes:
      - ./database/flyway/migrations:/flyway/migrations
    networks:
      - service-network
    depends_on:
      - mysqldb
    secrets:
      - flyway_config

  webapp:
    image: ${IMAGE_NAME:-todo-app}:latest
    container_name: ${IMAGE_NAME:-todo-app}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?sslMode=PREFERRED&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
    ports:
      - "8080:8080"
    networks:
      - service-network
    depends_on:
      - mysqldb
    secrets:
      - db_password
    restart: unless-stopped

volumes:
  db_data:

networks:
  service-network:
    driver: bridge

secrets:
  db_password:
    file: config/db_psswd.txt
  db_root_password:
    file: config/db_root_psswd.txt
  flyway_config:
    file: config/flyway.conf