services:
  mysqldb:
    image: mysql:9-oraclelinux9
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - service-network
    restart: unless-stopped

  flyway:
    image: flyway/flyway
    container_name: flyway_migration
    command: migrate -configFiles=/flyway/conf/flyway.toml
    volumes:
      - ./database/flyway/migrations:/flyway/migrations
      - ./database/flyway/conf:/flyway/conf
    networks:
      - service-network
    depends_on:
      - mysqldb

  webapp:
    image: ${IMAGE_NAME}:latest
    container_name: ${IMAGE_NAME}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?${DATABASE_OPTIONS}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - service-network
    depends_on:
      - mysqldb
    secrets:
      - db_password
    restart: unless-stopped

volumes:
  db_data:

networks:
  service-network:
    driver: bridge

secrets:
  db_password:
    file: ./db_pass.txt