CREATE TABLE IF NOT EXISTS `users` (

    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `password` VARCHAR(255),
    `roles` VARCHAR(255),
    `user_name` VARCHAR(255)

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;