# Database connection details
flyway.password=appdbdev
flyway.connectRetries=10

# Location of migration scripts (defaults to filesystem:sql)
flyway.locations=filesystem:/flyway/migrations

# Strategy for handling non-empty schemas
flyway.baselineOnMigrate=true

