flyway.url=jdbc:mysql://kashdebian:13306/appdbdev
flyway.user=appdbdev
flyway.password=appdbdev
#flyway.schemas=appdb001
flyway.locations=classpath:./migrations,filesystem:./migrations
flyway.cleanDisabled=false