INSERT INTO users (ID, PASSWORD, ROLES, USER_NAME) VALUES (0, '{bcrypt}$2a$10$UWdAXzBiG8w8Lfes9GMp0.3rfLgIm.mRxq58uYlT9uF5Rnn.KQOU.', 'ROLE_ADMIN,ROLE_USER', 'admin');
INSERT INTO users (ID, PASSWORD, ROLES, USER_NAME) VALUES (1, '{bcrypt}$2a$10$UWdAXzBiG8w8Lfes9GMp0.3rfLgIm.mRxq58uYlT9uF5Rnn.KQOU.', 'ROLE_USER', 'user');
